language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      install:
        - npm install -g jest codecov
      script:
        - jest && codecov
