language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      before_install:
        - npm install -g codecov
      script:
        - jest && codecov
